apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachineimports.v2v.kubevirt.io
spec:
  group: v2v.kubevirt.io
  names:
    kind: VirtualMachineImport
    listKind: VirtualMachineImportList
    plural: virtualmachineimports
    singular: virtualmachineimport
    shortNames:
    - vmimports
    categories:
    - all
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: 'VirtualMachineImportSpec defines the desired state of VirtualMachineImport'
          properties:
            providerCredentialsSecret:
              description: 'ProviderCredentialsSecret defines how a secret resource should be identified on kubevirt'
              properties:
                name:
                  description: 'Name defines the name of the secret for source provider credentials'
                  type: string
                namespace:
                  description: 'Namespace defines the namespace of the secret for source provider credentials'
                  type: string
            resourceMapping:
              description: 'ResourceMapping defines how a ResourceMapping should be identified on kubevirt. VM Import will map resources of source provider
                to kubevirt resources based on the mappings within ResourceMapping'
              properties:
                name:
                  description: 'Name defines the name of the ResourceMapping to use'
                  type: string
                namespace:
                  description: 'Namespace defines the namespace of the ResourceMapping to use'
                  type: string
            targetVmName:
              description: 'TargetVmName defines the name of the target VM to be created'
              type: string
            startVm:
              description: 'StartVm defines if the VM should be started at the end of the import process'
              type: boolean
            source:
              description: 'VirtualMachineImportSourceSpec defines the source provider and the internal mapping resources
              properties:
                ovirt:
                  description: 'VirtualMachineImportOvirtSourceSpec defines how to identify the VM in oVirt'
                  properties:
                    vm:
                      description: 'VirtualMachineImportOvirtSourceVMSpec defines the identification of the VM in oVirt'
                      properties:
                        id:
                          description: 'ID defines the ID of the VM in oVirt'
                          type: string
                        name:
                          description: 'Name defines the name of the VM in oVirt'
                          type: string
                        cluster:
                          description: 'VirtualMachineImportOvirtSourceVMClusterSpec defines the identification of source VM cluster in oVirt'
                          properties:
                            id:
                              description: 'ID defines the cluster ID in oVirt'
                              type: string
                            name:
                              description: 'ID defines the cluster name in oVirt'
                              type: string
                mappings:
                  description: 'OvirtMappings defines the mappings of ovirt resources to kubevirt'
                  properties:
                    networkMappings:
                      type: array
                    storageMappings:
                      type: array
                    diskMappings:
                      type: array
        status:
          properties:
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
