---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: vm-import-operator.0.0.2
  namespace: kubevirt-hyperconverged
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Represents a virtual machine import
      displayName: Virtual Machine import
      kind: VirtualMachineImport
      name: virtualmachineimports.v2v.kubevirt.io
      resources:
      - kind: ConfigMap
        name: vmimport-os-mapper
        version: v1
      specDescriptors:
      - description: The ImageRegistry to use for vm import.
        displayName: ImageRegistry
        path: imageRegistry
        x-descriptors:
        - urn:alm:descriptor:text
      - description: The ImageTag to use for vm import.
        displayName: ImageTag
        path: imageTag
        x-descriptors:
        - urn:alm:descriptor:text
      - description: The ImagePullPolicy to use for vm import.
        displayName: ImagePullPolicy
        path: imagePullPolicy
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:imagePullPolicy
      statusDescriptors:
      - description: The deployment phase.
        displayName: Phase
        path: phase
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.phase
      - description: Explanation for the current status of the vm import deployment.
        displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      - description: The observed version of the vm import deployment.
        displayName: Observed vm import Version
        path: observedVersion
        x-descriptors:
        - urn:alm:descriptor:text
      - description: The targeted version of the vm import deployment.
        displayName: Target vm import Version
        path: targetVersion
        x-descriptors:
        - urn:alm:descriptor:text
      - description: The version of the vm import Operator
        displayName: Vm import Operator Version
        path: operatorVersion
        x-descriptors:
        - urn:alm:descriptor:text
      version: v1alpha1
  description: VM import operator provides ability to import virtual machines from
    other infrastructure like oVirt/RHV
  displayName: VM import operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - vm-import-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - v2v.kubevirt.io
          resources:
          - '*'
          - resourcemappings
          verbs:
          - '*'
        - apiGroups:
          - kubevirt.io
          resources:
          - virtualmachines
          - virtualmachines/finalizers
          - virtualmachineinstances
          verbs:
          - '*'
        - apiGroups:
          - cdi.kubevirt.io
          resources:
          - datavolumes
          verbs:
          - '*'
        - apiGroups:
          - template.openshift.io
          resources:
          - templates
          verbs:
          - get
        - apiGroups:
          - template.openshift.io
          resources:
          - processedtemplates
          verbs:
          - create
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
        serviceAccountName: vm-import-operator
      deployments:
      - name: vm-import-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: vm-import-operator
              vm-import-operator: ""
          strategy: {}
          template:
            metadata:
              labels:
                name: vm-import-operator
                vm-import-operator: ""
            spec:
              containers:
              - command:
                - vm-import-operator
                env:
                - name: WATCH_NAMESPACE
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: vm-import-operator
                image: quay.io/masayag/vm-import-operator
                imagePullPolicy: Always
                name: vm-import-operator
                resources: {}
              serviceAccountName: vm-import-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Import
  - Virtualization
  - oVirt
  - RHV
  labels:
    operated-by: vm-import-operator
  links:
  - name: VM import operator
    url: https://github.com/kubevirt/vm-import-operator/blob/master/README.md
  - name: Source Code
    url: https://github.com/kubevirt/vm-import-operator/
  maintainers:
  - email: kubevirt-dev@googlegroups.com
    name: KubeVirt project
  maturity: alpha
  provider:
    name: KubeVirt project
  replaces: 0.0.0
  selector:
    matchLabels:
      operated-by: vm-import-operator
  version: 0.0.2
